- fe/src/components/common/SearchBar.tsx
- fe/src/components/ui/input.tsx
- fe/src/pages/RoomPage/index.tsx
#6 
- SearchBar UI
- react-icons와 Input 컴포넌트 이용하여 SearchBar UI 구현
> [FE] 방 검색 SearchBar 컴포넌트 생성

- fe/package-lock.json
- fe/package.json
- fe/src/components/ui/dialog.tsx
- fe/src/components/ui/label.tsx
- fe/src/pages/RoomPage/RoomDialog/RoomDialog.tsx
- fe/src/pages/RoomPage/RoomHeader/RoomHeader.tsx
- fe/src/types/room.ts
#7 
<br>
- RoomDialog 컴포넌트 UI 구현
<br>
- 방 제목과 닉네임을 설정할 수 있는 Dialog 컴포넌트 UI 구현
- 방 만들기 버튼 클릭 시 Dialog 띄우기
> [FE] 방 제목 및 닉네임 설정 Dialog 컴포넌트 생성

- .agt/agt.ps1
- .agt/agt.sh
Issue 기반으로 브랜치를 자동으로 생성해주는 스크립트를 작성했습니다.
자세한 사용 매뉴얼은 Wiki에 정리했습니다.
```
$ agt list
=== Open Issues ===
#2   [BE] 새로운 게임방을 생성한다.
#4   [BE] 개설된 게임방의 목록을 가져온다.
#8   [FE] 게임방 컴포넌트 생성
#9   [BE] 닉네임을 설정한다
```
```
$ agt branch
=== Open Issues ===
#2   [BE] 새로운 게임방을 생성한다.
#4   [BE] 개설된 게임방의 목록을 가져온다.
#8   [FE] 게임방 컴포넌트 생성
#9   [BE] 닉네임을 설정한다
Select issue number: 2
Creating and switching to branch: feature-be-#2 from dev-be
Successfully created and switched to branch: feature-be-#2
```
> chore: 이슈 기반 브랜치 자동 생성 스크립트 작성

- .agt/agt.sh
Bash 스크립트의 오타를 수정했습니다.
- Bash 스크립트 오타 수정
> chore: typo fix

- .github/workflows/auto-close-issue.yml
* 이슈 자동 종료 스크립트 수정
<br>
* 이슈 자동 종료 스크립트 수정
> chore: 이슈 자동 종료 스크립트 수정

- be/test1.txt
> [BE] 테스트 이슈 2

- .github/workflows/auto-close-issue.yml
* 이슈 자동 종료 스크립트 버그 수정(2)
<br>
* 이슈 자동 종료 스크립트 버그 수정(2)
> chore: 이슈 자동 종료 스크립트 버그 수정(2)

- .github/workflows/auto-close-issue.yml
* 이슈 자동 종료 스크립트 버그 수정(3)
<br>
* 이슈 자동 종료 스크립트 버그 수정(3)
> chore: 이슈 자동 종료 스크립트 버그 수정(3)

- be/test4.txt
> [BE] 테스트 이슈 4

- .agt/agt.ps1
- .agt/agt.sh
* AGT 버그 수정 및 안정성 개선
<br>
* AGT 버그 수정 및 안정성 개선
> chore: AGT 버그 수정 및 안정성 개선

- be/gameServer/src/modules/rooms/dto/create-room.dto.ts
- be/gameServer/src/modules/rooms/dto/room-data.dto.ts
- be/gameServer/src/modules/rooms/rooms.gateway.ts
- be/gameServer/src/modules/rooms/rooms.websocket.controller.ts
#9
* dto creatorNickname -> hostNickname 변경
> [BE] [hotfix] 닉네임을 설정한다 - 1

- ReadMe.md
- be/gameServer/src/modules/rooms/rooms.gateway.ts
- be/gameServer/src/modules/rooms/rooms.websocket.controller.ts
#54 
* socket disconnect 이벤트 처리
<br>
사용자, 게임방의 상태에 따라 다르게 처리되도록 했습니다.
* 사용자가 게임방의 host일 경우
다른 사용자에게 host를 넘겨줍니다.
* 게임방에 마지막으로 남은 경우
방을 삭제합니다
> [BE] - 사용자는 현재 게임방을 떠날 수 있다

- be/signalingServer/package-lock.json
- be/signalingServer/package.json
- be/signalingServer/src/config/app.config.js
- be/signalingServer/src/config/redis.config.js
- be/signalingServer/src/main.js
- be/signalingServer/src/services/redis.service.js
- be/signalingServer/src/services/socket.service.js
- be/signalingServer/src/static/index.html
#11
<br>
* 시그널링 서버를 구현하였습니다.
<br>
* 시그널링 서버를 구현하였습니다.
> [BE] 시그널링 서버 구현

- be/gameServer/src/main.ts
#71
* GameServer CORS 오류 해결
<br>
* HTTPS와 WSS 모두 CORS를 전면 허용할 수 있도록 설정을 수정함
> fix: GameServer CORS 오류 해결

- be/gameServer/package-lock.json
- be/gameServer/src/modules/rooms/rooms.controller.ts
- be/gameServer/src/modules/rooms/rooms.gateway.ts
- be/gameServer/src/redis/redis.service.ts
#82 
- redis pub/sub client 분리
- redis set, delete roomUpdate 채널 이벤트 송신 추가
- 게임방 목록 조회 get -> sse
pub, sub, 일반적 사용 을 위한 client를 분리했습니다.
> [`[SUBSCRIBE](https://deploy-preview-1964--redis-doc.netlify.app/commands/subscribe)`](https://deploy-preview-1964--redis-doc.netlify.app/commands/subscribe), [`[UNSUBSCRIBE](https://deploy-preview-1964--redis-doc.netlify.app/commands/unsubscribe)`](https://deploy-preview-1964--redis-doc.netlify.app/commands/unsubscribe) and [`[PUBLISH](https://deploy-preview-1964--redis-doc.netlify.app/commands/publish)`](https://deploy-preview-1964--redis-doc.netlify.app/commands/publish) implement the [[Publish/Subscribe messaging paradigm](http://en.wikipedia.org/wiki/Publish/subscribe)](http://en.wikipedia.org/wiki/Publish/subscribe) where (citing Wikipedia) …
> [BE] 게임방 목록의 변화를 실시간으로 반영할 수 있어야한다.

- be/gameServer/src/modules/rooms/rooms.controller.ts
#10 
* 특정 Room을 RoomId로 조회하는 API를 추가했습니다.
> [BE] 생성한 게임방의 링크를 GET 할 수 있다.

- be/gameServer/src/modules/rooms/rooms.controller.ts
> [BE] [hotfix] 게임방 목록의 변화를 실시간으로 반영할 수 있어야한다. - 2

- be/gameServer/src/app.module.ts
- be/gameServer/src/modules/games/games.gateway.ts
- be/gameServer/src/modules/games/games.module.ts
- be/gameServer/src/modules/games/games.websocket.emit.controller.ts
- be/gameServer/src/modules/games/games.websocket.on.controller.ts
- be/gameServer/src/modules/players/dto/player-data.dto.ts
- be/gameServer/src/modules/rooms/dto/room-data.dto.ts
- be/gameServer/src/modules/rooms/room-utils.ts
- be/gameServer/src/modules/rooms/rooms.gateway.spec.ts
- be/gameServer/src/modules/rooms/rooms.gateway.ts
- be/gameServer/src/modules/rooms/rooms.websocket.emit.controller.ts
- be/gameServer/src/modules/rooms/rooms.websocket.on.controller.ts
- be/gameServer/test/app.e2e-spec.ts
#109 
* player-data DTO 추가
* 준비 완료 기능 추가
* 준비 완료 테스트
* swagger 정리
> [BE] 사용자는 준비완료 상태를 나타낼 수 있다.

- be/gameServer/src/modules/rooms/rooms.gateway.spec.ts
- be/gameServer/src/modules/rooms/rooms.gateway.ts
- be/gameServer/src/modules/rooms/rooms.websocket.emit.controller.ts
- be/gameServer/src/modules/rooms/rooms.websocket.on.controller.ts
#115 
* setReady 수정
* 강퇴 기능 추가
준비 완료 상태로 만드는 것 뿐아니라 토글이 가능하도록 수정했습니다.
매개변수를 받지 않도록 수정했습니다.
unit, e2e 테스트를 추가했습니다
해당 내용 swagger에 업데이트했습니다.
> [BE] 호스트는 다른 사용자를 강퇴할 수 있다.

- be/gameServer/src/modules/rooms/rooms.gateway.ts
> [hotfix] [BE] 강퇴 후 updateUSers 이벤트 발행

- be/gameServer/src/modules/games/dto/turn-data.dto.ts
- be/gameServer/src/modules/games/games-utils.ts
- be/gameServer/src/modules/games/games.gateway.ts
- be/gameServer/src/modules/rooms/rooms.gateway.ts
#17 
* 클라이언트 연결 해제 시 데이터 처리
* random으로 게임 선택
* 발음 문제 샘플 데이터 추가
> [BE] 현재 단계를 음성 처리 서버, 클라이언트가 알 수 있어야한다.

- be/gameServer/src/modules/games/games.gateway.ts
- be/gameServer/src/modules/games/games.websocket.on.controller.ts
> [hotfix] [BE] 게임 시작시, 현재 단계의 진행을 결정한다.

- be/gameServer/src/modules/games/games.gateway.ts
- be/gameServer/src/modules/games/games.websocket.on.controller.ts
- be/gameServer/src/redis/redis.service.ts
#18 
* next 이벤트 추가
<br>
클라이언트에서 voiceResult 결과를 보여준 후 next 이벤트를 emit하면 turnChanged가 일어나도록 수정했습니다.
next이벤트를 게임방에서 한명이라도 먼저 emit하면 되도록 중복방지 처리를 했습니다.
> [hotfix] [BE] 게임 시작시, 현재 단계의 진행을 결정한다. 

- be/gameServer/src/modules/games/dto/game-data.dto.ts
- be/gameServer/src/modules/games/dto/voice-processing-result.dto.ts
- be/gameServer/src/modules/games/games-utils.ts
- be/gameServer/src/modules/games/games.gateway.ts
- be/gameServer/src/modules/games/games.websocket.emit.controller.ts
#142 
* endGame 이벤트 추가
살아남은 플레이어가 1명 일때 게임을 종료하기 위한 endGame 이벤트를 emit합니다.
이때 순위대로 플레이어 닉네임을 배열에 넣어 전달합니다.
swagger 업데이트 완료
> [BE] 사용자가 1명만 남았을 경우 게임을 종료한다.

- be/gameServer/src/modules/games/games.gateway.ts
> fix: 발음 게임 결과 로직 수정

- be/gameServer/src/modules/games/games.gateway.ts
#156 
feat: 게임 종료 시 게임 방 상태 waiting
> hotfix: 게임 종료 시 게임 방 상태 waiting

- fe/README.md
- fe/package-lock.json
- fe/package.json
- fe/src/App.tsx
- fe/src/pages/GamePage/index.tsx
- fe/src/pages/RoomListPage/RoomDialog/JoinDialog.tsx
#150
<br>
- 게임방 링크로 게임방 입장
- react-router-dom 다시 다운그레이드
<br>
- 게임방 링크로 접속 시 JoinDialog를 띄우고 닉네임 설정하여 게임방에 입장할 수 있도록 함
- v7 경고로 react-router-dom 업그레이드 했더니 라우팅 문제가 생겨 다시 다운그레이드 함
- 라우팅 문제: 방 나가기 시 방에서 나가기 처리가 안 됨
- 방 목록 페이지에서도 인원 수 변동 없음 
<br>
> [FE] 게임방 링크를 통해 게임방에 입장할 수 있다.

- be/gameServer/src/modules/rooms/rooms.controller.ts
- be/gameServer/src/modules/rooms/rooms.gateway.ts
- be/gameServer/src/redis/redis.service.ts
#157 
방 제목으로 검색 기능
auto complete 기능 포함
> [BE] 사용자는 방 제목을 검색할 수 있다.

- fe/src/pages/GamePage/index.tsx
#165
<br>
- 링크 복사 버튼 및 기능 구현
<br>
- 링크 복사 버튼 클릭 시 게임방 링크 클립보드에 복사
- 사용자에게 토스트 메시지 띄우기
- 토스트 메시지 화면 비율이 달라질 때 버튼들이 가려져서 오른쪽 아래에서 오른쪽 위로 위치 변경
<br>
> [FE] 링크 복사 버튼 및 기능 구현

- be/gameServer/src/modules/games/games-utils.ts
- be/gameServer/src/modules/games/games.gateway.ts
- be/gameServer/src/modules/rooms/rooms.gateway.ts
#18 
* 발음 게임 난이도 조정
* 점수 전송
* mute 이벤트 임시 분리
> Hotfix be #18 6

- fe/README.md
- fe/src/pages/GamePage/PlayerList/Player.tsx
- fe/src/pages/GamePage/index.tsx
- fe/src/services/gameSocket.ts
- fe/src/stores/zustand/useGameStore.ts
- fe/src/types/roomTypes.ts
- fe/src/types/socketTypes.ts
> [FE][hotfix] 음소거 상태 따로 분리하여 관리

- be/gameServer/src/modules/games/games-utils.ts
> 게임 테스트 용 랜덤 로직 변경

- be/gameServer/src/modules/rooms/rooms.controller.ts
#107 
fix: roomsList 정합성 문제
room을 삭제한 후 roomsList가 남아있어 null이 응답되는 현상 해결
> [hotfix] [BE] 개설된 게임방 페이지네이션

- be/gameServer/src/common/constant.ts
- be/gameServer/src/common/filters/ws-exceptions.filter.ts
- be/gameServer/src/modules/rooms/dto/create-room.dto.ts
- be/gameServer/src/modules/rooms/dto/join-data.dto.ts
- be/gameServer/src/modules/rooms/room-utils.ts
- be/gameServer/src/modules/rooms/rooms.controller.ts
- be/gameServer/src/modules/rooms/rooms.gateway.ts
- be/gameServer/src/modules/rooms/rooms.validation.pipe.ts
#83 
[방 이름 규칙 추가](https://github.com/boostcampwm-2024/web19-Clovapatra/commit/af80ddfa3faa649106288c5ee62f0dd932000692)
[rooms 상수 분리](https://github.com/boostcampwm-2024/web19-Clovapatra/commit/4354e222e9e5a1d9d476f59ca1d2ce3a8273c872)
[페이지 0부터로 변경](https://github.com/boostcampwm-2024/web19-Clovapatra/commit/8eb5110debb12c53aef6ca0aab2f51f0ffd71c48)
> [REFACTOR] [BE] 게임방 입장이 안되는 경우를 처리한다

- be/gameServer/src/common/constant.ts
- be/gameServer/src/modules/rooms/rooms.controller.ts
- be/gameServer/src/modules/rooms/rooms.gateway.ts
- be/gameServer/src/redis/redis.service.ts
#107 
[delete 시 redis 데이터 정합성 깨지는 문제 해결](https://github.com/boostcampwm-2024/web19-Clovapatra/commit/7d2f52d02a5159b677abc5d872dde06c7737f642)
> fix: delete 시 redis 데이터 정합성 깨지는 문제 해결

- be/gameServer/src/common/constant.ts
> chore: ROOMS_LIMIT 9로 변경

- .github/workflows/ncp_push.yml
- .nks/fe_Dockerfile
- .nks/game_Dockerfile
- .nks/signaling_Dockerfile
- .nks/voice_Dockerfile
> chore: nks 배포를 위한 Dockerfile 작성

- .github/workflows/ncp_push.yml
* NCP Source Commit에 Push할 때 전체 히스토리 Push하도록 수정
> fix: NCP Source Commit에 Push할 때 전체 히스토리 Push하도록 수정

- ReadMe.md
> docs: ReadMe 업데이트

- be/gameServer/src/modules/rooms/rooms.controller.ts
> feat:healthcheck API

- be/signalingServer/src/main.js
- be/voiceProcessingServer/src/main.js
#195
<br>
* signaling, voice 서버 health-check API 엔드포인트 생성
<br>
* signaling, voice 서버 health-check API 엔드포인트 생성
> [BE] signaling, voice 서버 health-check API 엔드포인트 생성

- fe/src/constants/errors.ts
- fe/src/hooks/useDialogForm.ts
- fe/src/pages/RoomListPage/RoomDialog/CreateDialog.tsx
- fe/src/pages/RoomListPage/RoomDialog/JoinDialog.tsx
- fe/src/utils/validator.ts
> [FE][hotfix] Input 필드 초기화 안 되는 문제 해결

- be/gameServer/src/modules/games/dto/voice-processing-result.dto.ts
- be/gameServer/src/modules/games/games-utils.ts
- be/gameServer/src/modules/games/games.gateway.ts
- be/gameServer/src/modules/games/games.websocket.emit.controller.ts
- be/gameServer/src/modules/rooms/dto/create-room.dto.ts
- be/gameServer/src/modules/rooms/dto/join-data.dto.ts
#204 
* voiceProcessingResult 이벤트 결과 수정
* swagger 업데이트
* 입력값 검증 보완
> 결과 화면 자세하게 띄우기

- be/gameServer/src/modules/games/games-utils.ts
- be/gameServer/src/modules/games/games.gateway.ts
> fix: 발음 게임 점수 후하게

- fe/README.md
- fe/src/components/ui/alert-dialog.tsx
- fe/src/hooks/useBackExit.ts
- fe/src/pages/RoomListPage/RoomDialog/JoinDialog.tsx
#211
<br>
- 링크로 게임방 입장 시 JoinDialog에서 취소 클릭하면 방 목록 페이지로 리다이렉션
- 새로고침 후 뒤로가기 하면 ExitDialog 취소 버튼에 포커싱되면서 아웃라인 생기는 부분 고침
<br>
> [FE][hotfix] JoinDialog 취소 시 리다이렉션 처리

- be/gameServer/src/modules/games/games.gateway.ts
- be/gameServer/src/modules/rooms/dto/create-room.dto.ts
- be/gameServer/src/modules/rooms/dto/join-data.dto.ts
#219 
* 입력값 정규식 수정
* 게임 음성 입력이 없을 때 처리
* 채점 서버 응답 try catch
* 소켓 연결 해제시 결과 처리
> [BE] 엣지 케이스

- be/gameServer/src/modules/games/games.gateway.ts
> [BE] fix: 0점시 탈락 처리

- be/gameServer/src/modules/games/games.gateway.ts
> [BE] fix: 탈주시 탈락처리

- be/gameServer/src/modules/games/games-utils.ts
> fix: rank 중복 제거

- fe/index.html
- fe/src/App.tsx
- fe/src/index.css
- fe/src/pages/GamePage/GameDialog/ExitDialog.tsx
- fe/src/pages/GamePage/index.tsx
- fe/src/pages/LandingPage/index.tsx
- fe/src/pages/RoomListPage/RoomDialog/JoinDialog.tsx
- fe/src/pages/RoomListPage/index.tsx
- fe/tailwind.config.js
#224
<br>
- LandingPage 컴포넌트 생성
- Pretendard 폰트 적용
- 게임 모드 GIF 넣기
- 배경 이미지 고정되도록 설정
- 라우팅 경로 변경
> [FE] 랜딩페이지 연결

- .github/workflows/ncp_push.yml
- .nks/clovapatra-fe.yaml
- .nks/clovapatra-game.yaml
- .nks/clovapatra-signaling.yaml
- .nks/clovapatra-voice.yaml
- .nks/voice_Dockerfile
* chore: SourceBuild 대신 Actions에서 빌드하도록 수정
<br>
> chore: SourceBuild 대신 Actions에서 빌드하도록 수정

- .nks/clovapatra-voice.yaml
> fix: domain typo fix

- .github/workflows/ncp_push.yml
chore: Github Secret .env 파일 경로 오타 수정
> chore: Github Secret .env 파일 경로 오타 수정

- .nks/ingress.yaml
* chore: ingress service name 오타 수정
> chore: ingress service name 오타 수정

- fe/src/pages/LandingPage/index.tsx
#238
<br>
* 랜딩 페이지 게임방 이동 버튼 URL 하드코딩 수정
<br>
* 랜딩 페이지 게임방 이동 버튼 URL 하드코딩 수정
> [FE] 랜딩 페이지 게임방 이동 버튼 URL 하드코딩 수정

- .nks/ingress.yaml
> chore: React routing 처리 수정

- .nks/be-ingress.yaml
- .nks/fe-ingress.yaml
* chore: NKS ingress admin 문제로 인한 버그 수정
> chore: NKS ingress admin 문제로 인한 버그 수정

- .nks/fe_Dockerfile
- .nks/nginx.conf
* chore: React Routing 문제 Dockerfile 수정으로 해결
> chore: React Routing 문제 Dockerfile 수정으로 해결

- be/gameServer/src/modules/games/games-utils.ts
- be/gameServer/src/modules/games/games.gateway.ts
> Hotfix be #219 5

- fe/package-lock.json
- fe/package.json
- fe/src/components/common/GameModeSelector.tsx
- fe/src/components/common/RoomOptionsSlider.tsx
- fe/src/components/ui/radio-group.tsx
- fe/src/pages/RoomListPage/RoomDialog/CreateDialog.tsx
- fe/src/pages/RoomListPage/RoomList/GameRoom.tsx
- fe/src/services/gameSocket.ts
- fe/src/types/roomTypes.ts
#249
<br>
* 게임 모드 선택 및 방 최대 인원 조절 기능 추가
<br>
* 게임 모드 선택 및 방 최대 인원 조절 기능 추가
> [FE] 게임 모드 선택 및 방 최대 인원 조절 기능 추가

- fe/package-lock.json
- fe/package.json
- fe/src/pages/GamePage/GameScreen/EndScreen.tsx
- fe/src/pages/GamePage/GameScreen/PlayScreen.tsx
- fe/src/pages/GamePage/GameScreen/ReadyScreen.tsx
- fe/src/pages/GamePage/index.tsx
#253
<br>
- GamePage 콘텐츠 중앙 배치
- 시상대 플레이어 닉네임 중앙 배치
<br>
> [FE] GamePage 및 시상대 CSS 수정
